#!/usr/bin/env bash
#~encodes existing library to mp4 with aac audio
#~or downloads videos with ytdl and lolifys them (uses .netrc for auth)

#~ config ~#


#~ functions ~#

_help() {
    echo "
    usage:  lolify [options]

    options:

        -h  show this message
    

        -yt [link]
            using this option changes the default audio track
            to 1:a:0 since the majority of the time ytdl will
            download seperate video and audio files, thus the FID
            is 1 instead of 0

        -t  [audio track]
            defualt=0:a:0 (the first audio track)
            (the first 0 is the input FID or file id
            the 'a' means we want audio
            the last 0 is the TID or which audio file we want

        -s  [source dir]
            the one w/ the non mp4s
            default=./

        -d  [destination dir]
            where you want the mp4s
            defualt=./lolified
    "
}

_library(){
    #~encode existing library

    #~re-create directory structure
    find "$sourceDir" -type d -not -path "*$destDir*" -exec bash -c 'destPath="$2/${1#*"$3"}"; echo "item:$destPath"; mkdir -p "$destPath"' - {} "$destDir" "$sourceDir" \;

    #~encode files
    find "$sourceDir" -type f -not -path "*$destDir*" -exec bash -c 'destPath="$2/${1#*"$3"}"; echo "item:$destPath"; ffmpeg -v quiet -stats -i "$1" -map 0:v:0 -map "$4" -movflags +faststart -c:v libx264 -preset slower -crf 19 -ac 2 -c:a aac -b:a 192k "${destPath%.*}.mp4"' - {} "$destDir" "$sourceDir" "$trackID" \;
}

_ytdl(){
    #~encode files downloaded by ytdl

    if [[ "$ytdlLink" == *"http"* ]]; then
        youtube-dl "$1" --netrc --no-continue --ignore-errors --format bestvideo+bestaudio --merge-output-format mp4 --postprocessor-args "-v quiet -stats -movflags +faststart -c:v libx264 -preset slower -crf 19 -ac 2 -c:a aac -b:a 192k" --output "$destDir/%(uploader)s/%(title)s-%(id)s.%(ext)s"
    else
        echo no link provided, exiting
        exit
    fi

}


#~ script_start ~#

while [ "$1" != "" ]; do
    case $1 in
        *help)
            _help
            exit
           ;;
       -t)
           shift
           trackID="$1"
           ;;
       -s)
           shift
           sourceDir="$1"
           ;;
       -d)
           shift
           destDir="$1"
           ;;
       -yt)
           shift
           ytdlLink="$1"
           ytdl=true
           ;;
       *)
           echo "unknown option: '$1'"
           _help
           exit 1
           ;;
   esac
   shift
done
#defaults
trackID="${trackID:-0:a:0}"
sourceDir="${sourceDir:-.}"
destDir="${destDir:-./lolified}"
ytdl="${ytdl:-false}"

echo source:$sourceDir
echo dest:$destDir
echo trackID:$trackID

if [[ "$ytdl" == "true" ]]; then
    _ytdl "$ytdlLink"
else
    _library
fi

echo Done.
